# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huruf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huruf', models.CharField(max_length=50)),
                ('cover', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SignLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signlanguage_name', models.CharField(max_length=40)),
                ('website', models.CharField(max_length=40)),
                ('signlanguage_logo', models.FileField(upload_to='')),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='huruf',
            name='signlanguage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycollections.SignLanguage'),
        ),
    ]
